name: EMHASS
description: Energy Management for Home Assistant
url: https://github.com/onIon-energy/emhass
version: 0.5.4-testonion
slug: emhass
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
#image: "davidusb/image-{arch}-emhass"
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface and API
webui: http://[HOST]:[PORT:5000]
map:
  - config:rw
  - share:rw
init: false
hassio_role: default
homeassistant_api: true
ingress: true
ingress_port: 5000
ingress_stream: true
options:
  hass_url: empty
  long_lived_token: empty
  costfun: profit
  logging_level: INFO
  optimization_time_step: 30
  historic_days_to_retrieve: 2
  method_ts_round: nearest
  set_total_pv_sell: false
  lp_solver: COIN_CMD
  lp_solver_path: /usr/bin/cbc
  set_nocharge_from_grid: false
  set_nodischarge_to_grid: false
  set_battery_dynamic: false
  battery_dynamic_max: 0.9
  battery_dynamic_min: -0.9
  weight_battery_discharge: 1.0
  weight_battery_charge: 1.0
  load_forecast_method: "naive"
  sensor_power_photovoltaics: sensor.power_photovoltaics
  sensor_power_load_no_var_loads: sensor.power_load_no_var_loads
  number_of_deferrable_loads: 2
  list_nominal_power_of_deferrable_loads:
    - nominal_power_of_deferrable_loads: 3000
    - nominal_power_of_deferrable_loads: 750
  list_operating_hours_of_each_deferrable_load:
    - operating_hours_of_each_deferrable_load: 5
    - operating_hours_of_each_deferrable_load: 8
  list_start_timesteps_of_each_deferrable_load:
    - start_timesteps_of_each_deferrable_load: 0
    - start_timesteps_of_each_deferrable_load: 0
  list_end_timesteps_of_each_deferrable_load:
    - end_timesteps_of_each_deferrable_load: 0
    - end_timesteps_of_each_deferrable_load: 0
  list_peak_hours_periods_start_hours:
    - peak_hours_periods_start_hours: 05:54
    - peak_hours_periods_start_hours: 10:24
  list_peak_hours_periods_end_hours:
    - peak_hours_periods_end_hours: 09:24
    - peak_hours_periods_end_hours: 11:54
  list_treat_deferrable_load_as_semi_cont:
    - treat_deferrable_load_as_semi_cont: true
    - treat_deferrable_load_as_semi_cont: true
  load_peak_hours_cost: 0.1907
  load_offpeak_hours_cost: 0.1419
  photovoltaic_production_sell_price: 0.065
  maximum_power_from_grid: 9000
  list_pv_module_model:
    - pv_module_model: CSUN_Eurasia_Energy_Systems_Industry_and_Trade_CSUN295_60M
  list_pv_inverter_model:
    - pv_inverter_model: Fronius_International_GmbH__Fronius_Primo_5_0_1_208_240__240V_
  list_surface_tilt:
    - surface_tilt: 30
  list_surface_azimuth:
    - surface_azimuth: 205
  list_modules_per_string:
    - modules_per_string: 16
  list_strings_per_inverter:
    - strings_per_inverter: 1
  set_use_battery: false
  battery_discharge_power_max: 1000
  battery_charge_power_max: 1000
  battery_discharge_efficiency: 0.95
  battery_charge_efficiency: 0.95
  battery_nominal_energy_capacity: 5000
  battery_minimum_state_of_charge: 0.3
  battery_maximum_state_of_charge: 0.9
  battery_target_state_of_charge: 0.6
schema:
  hass_url: str
  long_lived_token: str
  costfun: list(profit|cost|self-consumption)
  logging_level: list(DEBUG|INFO|WARNING|ERROR)
  optimization_time_step: int(10,1440)
  historic_days_to_retrieve: int(2,365)
  method_ts_round: str
  set_total_pv_sell: bool
  lp_solver: str
  lp_solver_path: str
  set_nocharge_from_grid: bool
  set_nodischarge_to_grid: bool
  set_battery_dynamic: bool
  battery_dynamic_max: float(0.0,1.0)
  battery_dynamic_min: float
  weight_battery_discharge: float
  weight_battery_charge: float
  load_forecast_method: str
  sensor_power_photovoltaics: str
  sensor_power_load_no_var_loads: str
  number_of_deferrable_loads: int(1,10)
  list_nominal_power_of_deferrable_loads:
    - nominal_power_of_deferrable_loads: int(0,)
  list_operating_hours_of_each_deferrable_load:
    - operating_hours_of_each_deferrable_load: int(0,)
  list_start_timesteps_of_each_deferrable_load:
    - start_timesteps_of_each_deferrable_load: int(0,)
  list_end_timesteps_of_each_deferrable_load:
    - end_timesteps_of_each_deferrable_load: int(0,)
  list_peak_hours_periods_start_hours:
    - peak_hours_periods_start_hours: str
  list_peak_hours_periods_end_hours:
    - peak_hours_periods_end_hours: str
  list_treat_deferrable_load_as_semi_cont:
    - treat_deferrable_load_as_semi_cont: bool
  load_peak_hours_cost: float(0,)
  load_offpeak_hours_cost: float(0,)
  photovoltaic_production_sell_price: float(0,)
  maximum_power_from_grid: int(0,)
  list_pv_module_model:
    - pv_module_model: str
  list_pv_inverter_model:
    - pv_inverter_model: str
  list_surface_tilt:
    - surface_tilt: int(0,90)
  list_surface_azimuth:
    - surface_azimuth: int(0,360)
  list_modules_per_string:
    - modules_per_string: int(0,)
  list_strings_per_inverter:
    - strings_per_inverter: int(0,)
  set_use_battery: bool
  battery_discharge_power_max: int(0,)
  battery_charge_power_max: int(0,)
  battery_discharge_efficiency: float(0.0,1.0)
  battery_charge_efficiency: float(0.0,1.0)
  battery_nominal_energy_capacity: int(0,)
  battery_minimum_state_of_charge: float(0.0,1.0)
  battery_maximum_state_of_charge: float(0.0,1.0)
  battery_target_state_of_charge: float(0.0,1.0)
